// Les sept époques du jeu. Chaque époque modifie palette, ambiance, props
// affichés dans le monde, PNJ disponibles, quêtes et bande-son.
// Chaque époque se déroule dans UNE ville de l'île (champ `town`) :
// le voyage temporel téléporte le joueur dans la ville de l'époque.

export const ERAS = [
  {
    id: 'prehistoire',
    name: 'Préhistoire',
    years: '~6000 av. J.-C.',
    town: 'portes',
    townName: 'Les Portes-en-Ré',
    blurb: 'Campement de chasseurs aux Portes, dunes sauvages, dolmens.',
    sky: { day: 0x9cb8c8, night: 0x081018, horizon: 0xa89878 },
    fog: { color: 0x8aa094, density: 0.018 },
    ground: 0x5a6b3a,
    vegetationDensity: 1.4,
    sea: 0x4a6878,
    architecture: 'huts',
    music: 'ambient_primal',
    icon: '⛰',
  },
  {
    id: 'antiquite',
    name: 'Antiquité romaine',
    years: 'Iᵉʳ siècle',
    town: 'sainte-marie',
    townName: 'Sainte-Marie-de-Ré',
    blurb: 'Débarquement romain à Sainte-Marie : villa, entrepôt, commerce du sel et du vin.',
    sky: { day: 0x88aacc, night: 0x0a1828, horizon: 0xd4b078 },
    fog: { color: 0xa8b8c4, density: 0.012 },
    ground: 0x7a7848,
    vegetationDensity: 1.0,
    sea: 0x3a6888,
    architecture: 'roman',
    music: 'ambient_antique',
    icon: '🏛',
  },
  {
    id: 'moyenage',
    name: 'Moyen Âge',
    years: 'XIIᵉ–XIVᵉ siècle',
    town: 'flotte',
    townName: 'La Flotte',
    blurb: 'La Flotte : halles, port médiéval, chantier de l\'abbaye des Châteliers.',
    sky: { day: 0x7a98b8, night: 0x081020, horizon: 0xb8967a },
    fog: { color: 0x8a98a8, density: 0.014 },
    ground: 0x6a6a3a,
    vegetationDensity: 1.1,
    sea: 0x365a78,
    architecture: 'medieval',
    music: 'ambient_medieval',
    icon: '⚔',
  },
  {
    id: 'xvii',
    name: 'XVIIᵉ siècle',
    years: '1627–1685',
    town: 'saint-martin',
    townName: 'Saint-Martin-de-Ré',
    blurb: 'Saint-Martin fortifié par Vauban : remparts en étoile, citadelle, port de guerre.',
    sky: { day: 0x88a8c4, night: 0x0a1424, horizon: 0xc4a878 },
    fog: { color: 0x98a4b0, density: 0.010 },
    ground: 0x6a6a48,
    vegetationDensity: 0.9,
    sea: 0x305878,
    architecture: 'xvii',
    music: 'ambient_baroque',
    icon: '⚜',
  },
  {
    id: 'xix',
    name: 'XIXᵉ siècle',
    years: '1820–1900',
    town: 'ars',
    townName: 'Ars-en-Ré',
    blurb: 'Ars, capitale du sel : clocher noir et blanc, marais salants, gabarres au port.',
    sky: { day: 0x9ab4cc, night: 0x0a1828, horizon: 0xd4b888 },
    fog: { color: 0xa4b0bc, density: 0.008 },
    ground: 0x7a7a48,
    vegetationDensity: 0.85,
    sea: 0x305a7c,
    architecture: 'xix',
    music: 'ambient_xix',
    icon: '⚓',
  },
  {
    id: 'wwii',
    name: 'Seconde Guerre mondiale',
    years: '1940–1945',
    town: 'bois-plage',
    townName: 'Le Bois-Plage-en-Ré',
    blurb: 'Le Bois-Plage occupé : bunkers du Mur de l\'Atlantique dans les dunes, résistance.',
    sky: { day: 0x6a7888, night: 0x050a14, horizon: 0x887860 },
    fog: { color: 0x788490, density: 0.020 },
    ground: 0x5a5a3a,
    vegetationDensity: 0.7,
    sea: 0x244858,
    architecture: 'wwii',
    music: 'ambient_war',
    icon: '⚙',
  },
  {
    id: 'contemporaine',
    name: 'Époque contemporaine',
    years: '2020+',
    town: 'phare-baleines',
    townName: 'Phare des Baleines',
    blurb: 'Le Phare des Baleines aujourd\'hui : musée, pistes cyclables, patrimoine préservé.',
    sky: { day: 0xa4c4dc, night: 0x081428, horizon: 0xe4c898 },
    fog: { color: 0xb0c0d0, density: 0.006 },
    ground: 0x848248,
    vegetationDensity: 1.0,
    sea: 0x2a6090,
    architecture: 'contemporary',
    music: 'ambient_modern',
    icon: '🚲',
  },
];

export const ERA_INDEX = Object.fromEntries(ERAS.map((e, i) => [e.id, i]));

export function getEra(id) {
  return ERAS[ERA_INDEX[id]];
}
